# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

export OPENSSL_DIR=$(brew --prefix openssl@3)
export OPENSSL_INCLUDE_DIR=$(brew --prefix openssl@3)/include
export PATH="/opt/homebrew/opt/ruby/bin:$PATH"
export OPENAI_API_KEY=dummy
export CODEX_HOME=~/.codex/


# If you come from bash you might have to change your $PATH.
# export PATH=$HOME/bin:$HOME/.local/bin:/usr/local/bin:$PATH

# Path to your Oh My Zsh installation.
export ZSH="$HOME/.oh-my-zsh"

# Set name of the theme to load --- if set to "random", it will
# load a random theme each time Oh My Zsh is loaded, in which case,
# to know which specific one was loaded, run: echo $RANDOM_THEME
# See https://github.com/ohmyzsh/ohmyzsh/wiki/Themes
ZSH_THEME="powerlevel10k/powerlevel10k"

# Set list of themes to pick from when loading at random
# Setting this variable when ZSH_THEME=random will cause zsh to load
# a theme from this variable instead of looking in $ZSH/themes/
# If set to an empty array, this variable will have no effect.
# ZSH_THEME_RANDOM_CANDIDATES=( "robbyrussell" "agnoster" )

# Uncomment the following line to use case-sensitive completion.
# CASE_SENSITIVE="true"

# Uncomment the following line to use hyphen-insensitive completion.
# Case-sensitive completion must be off. _ and - will be interchangeable.
# HYPHEN_INSENSITIVE="true"

# Uncomment one of the following lines to change the auto-update behavior
# zstyle ':omz:update' mode disabled  # disable automatic updates
# zstyle ':omz:update' mode auto      # update automatically without asking
# zstyle ':omz:update' mode reminder  # just remind me to update when it's time

# Uncomment the following line to change how often to auto-update (in days).
# zstyle ':omz:update' frequency 13

# Uncomment the following line if pasting URLs and other text is messed up.
# DISABLE_MAGIC_FUNCTIONS="true"

# Uncomment the following line to disable colors in ls.
# DISABLE_LS_COLORS="true"

# Uncomment the following line to disable auto-setting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment the following line to enable command auto-correction.
# ENABLE_CORRECTION="true"

# Uncomment the following line to display red dots whilst waiting for completion.
# You can also set it to another string to have that shown instead of the default red dots.
# e.g. COMPLETION_WAITING_DOTS="%F{yellow}waiting...%f"
# Caution: this setting can cause issues with multiline prompts in zsh < 5.7.1 (see #5765)
# COMPLETION_WAITING_DOTS="true"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Uncomment the following line if you want to change the command execution time
# stamp shown in the history command output.
# You can set one of the optional three formats:
# "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
# or set a custom format using the strftime function format specifications,
# see 'man strftime' for details.
# HIST_STAMPS="mm/dd/yyyy"

# Would you like to use another custom folder than $ZSH/custom?
# ZSH_CUSTOM=/path/to/new-custom-folder

# Which plugins would you like to load?
# Standard plugins can be found in $ZSH/plugins/
# Custom plugins may be added to $ZSH_CUSTOM/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(
  git
  zsh-autosuggestions
  zsh-syntax-highlighting
  fast-syntax-highlighting
  zsh-autocomplete
  zsh-history-substring-search
  zsh-interactive-cd
  zsh-autopair
  zsh-you-should-use
)
source $ZSH/oh-my-zsh.sh

# User configuration

# export MANPATH="/usr/local/man:$MANPATH"

# You may need to manually set your language environment
# export LANG=en_US.UTF-8

# Preferred editor for local and remote sessions
# if [[ -n $SSH_CONNECTION ]]; then
#   export EDITOR='vim'
# else
#   export EDITOR='nvim'
# fi

# Compilation flags
# export ARCHFLAGS="-arch $(uname -m)"

# Set personal aliases, overriding those provided by Oh My Zsh libs,
# plugins, and themes. Aliases can be placed here, though Oh My Zsh
# users are encouraged to define aliases within a top-level file in
# the $ZSH_CUSTOM folder, with .zsh extension. Examples:
# - $ZSH_CUSTOM/aliases.zsh
# - $ZSH_CUSTOM/macos.zsh
# For a full list of active aliases, run `alias`.
#
# Example aliases
# alias zshconfig="mate ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"
export EDITOR='nvim'
alias v="nvim"
alias r="rm -rf"

# Netflix
alias spin-health="$HOME/spin-helper/run-spinnaker-health.sh"
alias topo="$HOME/spin-helper/run-topo.sh"
alias spin="newt spin browse"
alias bro="newt source browse"
alias je="newt ci browse"
alias bb="./gradlew build"
alias spot="./gradlew spotlessApply"

# EZ config aliases
alias zshconfig="v ~/.zshrc"
alias ohmyzsh="v ~/.oh-my-zsh"
alias zshsource="source ~/.zshrc"
alias ax="cd ~/IdeaProjects/" 
alias claude="headroom wrap claude --model opus --permission-mode auto"
alias ls='eza -lh --git --group-directories-first -s extension --icons'

# Git Aliases
alias ga="git add"
alias gc="git commit -m"
alias gr="git rebase -i"
alias gcb="git checkout"
alias amend="git commit --amend"
alias log="git log"
alias pull="git pull"
# alias push="git push --set-upstream origin $(git rev-parse --abbrev-ref HEAD)"
alias c="clear"
alias diff="git diff"
alias stash="git stash"

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh

# >>> conda initialize >>>
# !! Contents within this block are managed by 'conda init' !!
__conda_setup="$('/Users/omes/miniconda3/bin/conda' 'shell.zsh' 'hook' 2> /dev/null)"
if [ $? -eq 0 ]; then
    eval "$__conda_setup"
else
    if [ -f "/Users/omes/miniconda3/etc/profile.d/conda.sh" ]; then
        . "/Users/omes/miniconda3/etc/profile.d/conda.sh"
    else
        export PATH="/Users/omes/miniconda3/bin:$PATH"
    fi
fi
unset __conda_setup
# <<< conda initialize <<<


function shard() {
  grpc -a dgwcontrol.kv -e $1 -r us-east-1 com.netflix.dgw.control.DgwControlService/GetNamespaces -d "{\"shard_identity\": \"$2\"}"
}

function cluster() {
  grpc -a dgwcontrol.kv -e "$1" com.netflix.dgw.control.DgwControlService/GetNamespaces -d "{\"namespaceFilters\": [ { \"physicalClusterName\": \"$2\", \"include_shard_info\": true} ]}"
}


function namespace () {
  grpc -a dgwcontrol.kv -e "$1" com.netflix.dgw.control.DgwControlService/GetNamespaces -d "{\"namespaceFilters\": [ { \"match_name\": \"$2\", \"include_shard_info\": true} ]}"
}

function ghrepo() {
  if [[ -e .git/ ]]; then
    $(which gh) -R corp/$(basename $PWD) "$@"
  else
    $(which gh) "$@"
  fi
}


export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
export JAVA_HOME="/opt/homebrew/opt/openjdk@21"
export PATH="/opt/homebrew/opt/openjdk@21/bin:$PATH"

# Git worktree helper
gw() {
  local name="$1"
  if [[ -z "$name" ]]; then
    echo "Usage: gw <name>"
    return 1
  fi

  local root
  root=$(git rev-parse --show-toplevel 2>/dev/null) || { echo "Not in a git repo"; return 1; }

  # Check if worktree already exists
  local dir_name="${name//\//-}"
  local wt_path
  wt_path=$(git worktree list --porcelain | awk -v name="/$dir_name" '$1=="worktree" && $0 ~ name"$" {print $2}')

  if [[ -n "$wt_path" ]]; then
    cd "$wt_path"
  else
    local repo_name="${root##*/}"
    local track
    if [[ "$repo_name" == "cde-nfcassandra" ]]; then
      track="origin/cassandra-4.1"
    else
      track="origin/master"
      if ! git rev-parse --verify "$track" &>/dev/null; then
        track="origin/release/main"
      fi
    fi
    if ! git rev-parse --verify "$track" &>/dev/null; then
      echo "Could not find branch $track"
      return 1
    fi

    local dir_name="${name//\//-}"
    local dest="$root/.worktrees/$dir_name"
    if git rev-parse --verify "$name" &>/dev/null; then
      git worktree add "$dest" "$name" && cd "$dest"
    else
      git worktree add -b "$name" "$dest" "$track" && cd "$dest" && git branch --unset-upstream "$name"
    fi
  fi
}
